### ISSUE TITLE
Extend support for Rails environments?

### ISSUE THREAD

**Issue by jrnk** [npearson72/rails-ahoy#1]
First of all: Thanks for this gem! It looks very useful and uses the same stack as I am using most of the time (I found it while googleing on the stack pref).
Looking through the code it seems focused on the production environment, however it mentions the environment a couple of times in the README. So i'm confused about how I would use it to generate f.e. a staging and production deployment env's, could you shed some light on this?
Thanks!

**Comment by npearson72** [comment]
Once you initialize the generator, it will create all the files you need for production. You would need to copy a few files and name them according to the environments you want.

The first file you'll want to copy is:

`.env/production_env.yml` and name it `staging_env.yml`

Then go to:

config/ansible and in the `host` file add a block like so:
````
[staging]
root ansible_ssh_host=<your staging server ip>
deploy ansible_ssh_host=<your staging server ip>
````

There should already be a block like this there for production, so just copy and adjust it.

Next you're want to copy:

`config/ansible/playbooks/production.yml` and rename it to `staging.yml`

Then you'll want to create the following symlink:
````
$cd config/ansible/playbook/group_vars
$ln -s ../../../../.env/staging_env.yml staging.yml
````

That should get your ansible scripts working so that you can deploy to either production or staging like so...

````
$cd config/ansible
$./provision staging
````

To deploy, you'll need to modify what's in `config/deploy.rb`

Mine looks like this:
````
require 'mina/bundler'
require 'mina/rails'
require 'mina/git'
require 'mina/rbenv'

set :deploy_to,     '/var/www/your app dir on the server'
set :app_path,      '/var/www/your app dir on the server/current'
set :user,          'deploy'
set :port,          'your ssh port.. probably 22'
set :repository,    'Your git repo'
set :forward_agent, true

task :staging do
  set :domain,        'your staging server ip'
  set :branch,        'dev <-- this is the branch I use for deploying to staging'
  set :rails_env,     'staging'
  set :shared_paths,  ['config/database.yml', 'config/secrets.yml', 'log', 'tmp', '.env/staging_env.yml']
end

task :production do
  set :domain,        'your production server ip'
  set :branch,        'master <-- this git branch is used for production'
  set :rails_env,     'production'
  set :shared_paths,  ['config/database.yml', 'config/secrets.yml', 'log', 'tmp', '.env/production_env.yml']
end

task :environment do
  queue 'export PATH=/usr/local/rbenv/bin:/usr/local/rbenv/shims:$PATH'
  queue 'source ~/.session_vars'
end

task setup: :environment do
  queue "mkdir -m 750 -p #{deploy_to}/#{shared_path}/log"
  queue "mkdir -m 750 -p #{deploy_to}/#{shared_path}/config"
  queue "mkdir -m 750 -p #{deploy_to}/#{shared_path}/tmp/log"
  queue "mkdir -m 750 -p #{deploy_to}/#{shared_path}/tmp/pids"
  queue "mkdir -m 750 -p #{deploy_to}/#{shared_path}/tmp/sockets"
end

namespace :rails do
  task db_seed: :environment do
    queue "cd #{app_path}"
    queue "bundle exec rake db:seed RAILS_ENV=#{rails_env}"
  end
end

namespace :server do
  task start: :environment do
    queue "cd #{app_path} && rails_env=#{rails_env} && bin/puma.sh start"
  end

  task stop: :environment do
    queue "cd #{app_path} && rails_env=#{rails_env} && bin/puma.sh stop"
  end

  task restart: :environment do
    queue "cd #{app_path} && rails_env=#{rails_env} && bin/puma.sh restart"
  end
end

task deploy: :environment do
  deploy do
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'
    invoke :'bundle:install'
    invoke :'rails:db_migrate'
    invoke :'rails:assets_precompile'
    invoke :'deploy:cleanup'
    to :launch do
      invoke :'server:restart'
    end
  end
end
````

**Comment by jrnk** [comment]
Thanks Nathan!

**Comment by npearson72** [comment]
No problem. BTW, the `.env` folder is ignored by git to keep the info there private. So sine it's never committed with your code, it's a good idea to back it up somehow. I usually put my in my Dropbox folder and symlink it to my project root.
